import brand1 from '@/assets/img/brands/brand01.png';
import brand2 from '@/assets/img/brands/brand02.png';
import brand3 from '@/assets/img/brands/brand03.png';
import brand4 from '@/assets/img/brands/brand04.png';
import brand5 from '@/assets/img/brands/brand05.png';
import brand6 from '@/assets/img/brands/brand06.png';
import brand8 from '@/assets/img/brands/brand08.png';
import brand9 from '@/assets/img/brands/brand09.png';

export const brands = [brand1, brand2, brand3, brand4, brand5, brand6, brand8, brand9];

export interface Product {
  id: number;
  name: string;
  image: string;
  priceMin: number;
  priceMax: number;
  rating?: number;
  reviewCount?: number;
  inStock?: boolean;
  discountPercentage?: number;
}

export const laptopsData: Product[] = [
  {
    id: 1,
    name: 'Lenovo Idea Pad',
    image: '/lenovo-laptop-silver.jpg',
    priceMin: 140,
    priceMax: 160,
    rating: 5,
    reviewCount: 2,
    inStock: true,
    discountPercentage: 15,
  },
  {
    id: 2,
    name: 'MacBook Pro 16',
    image: '/macbook-pro-laptop.png',
    priceMin: 2399,
    priceMax: 2899,
    rating: 4,
    reviewCount: 15,
    inStock: true,
  },
  {
    id: 3,
    name: 'Dell XPS 15',
    image: '/lenovo-laptop-silver.jpg',
    priceMin: 1299,
    priceMax: 1799,
    rating: 5,
    reviewCount: 28,
    inStock: true,
    discountPercentage: 20,
  },
  {
    id: 4,
    name: 'HP Pavilion',
    image: '/macbook-pro-laptop.png',
    priceMin: 699,
    priceMax: 899,
    rating: 4,
    reviewCount: 12,
    inStock: false,
  },
  {
    id: 5,
    name: 'ASUS ROG Strix',
    image: '/lenovo-laptop-silver.jpg',
    priceMin: 1599,
    priceMax: 2199,
    rating: 5,
    reviewCount: 34,
    inStock: true,
    discountPercentage: 10,
  },
  {
    id: 6,
    name: 'Acer Aspire',
    image: '/macbook-pro-laptop.png',
    priceMin: 549,
    priceMax: 749,
    rating: 3,
    reviewCount: 8,
    inStock: true,
    discountPercentage: 25,
  },
  {
    id: 7,
    name: 'Microsoft Surface Laptop',
    image: '/lenovo-laptop-silver.jpg',
    priceMin: 999,
    priceMax: 1499,
    rating: 4,
    reviewCount: 22,
    inStock: true,
  },
  {
    id: 8,
    name: 'Razer Blade 15',
    image: '/macbook-pro-laptop.png',
    priceMin: 1799,
    priceMax: 2499,
    rating: 5,
    reviewCount: 41,
    inStock: true,
    discountPercentage: 12,
  },
  {
    id: 9,
    name: 'Lenovo ThinkPad X1',
    image: '/lenovo-laptop-silver.jpg',
    priceMin: 1399,
    priceMax: 1899,
    rating: 5,
    reviewCount: 56,
    inStock: true,
  },
  {
    id: 10,
    name: 'MSI Prestige 14',
    image: '/macbook-pro-laptop.png',
    priceMin: 1099,
    priceMax: 1399,
    rating: 4,
    reviewCount: 18,
    inStock: false,
    discountPercentage: 18,
  },
  {
    id: 11,
    name: 'Samsung Galaxy Book',
    image: '/lenovo-laptop-silver.jpg',
    priceMin: 849,
    priceMax: 1149,
    rating: 4,
    reviewCount: 14,
    inStock: true,
  },
  {
    id: 12,
    name: 'LG Gram 17',
    image: '/macbook-pro-laptop.png',
    priceMin: 1599,
    priceMax: 1899,
    rating: 5,
    reviewCount: 31,
    inStock: true,
    discountPercentage: 8,
  },
];

export const accessoriesData: Product[] = [
  {
    id: 13,
    name: '8K Camera',
    image: '/dslr-camera-black.jpg',
    priceMin: 25,
    priceMax: 29,
    rating: 4,
    reviewCount: 18,
    inStock: true,
    discountPercentage: 30,
  },
  {
    id: 14,
    name: 'Wireless Mouse',
    image: '/wireless-mouse.png',
    priceMin: 15,
    priceMax: 25,
    rating: 5,
    reviewCount: 42,
    inStock: true,
  },
  {
    id: 15,
    name: 'USB-C Hub',
    image: '/usb-c-hub-adapter.jpg',
    priceMin: 35,
    priceMax: 45,
    rating: 4,
    reviewCount: 27,
    inStock: true,
    discountPercentage: 15,
  },
  {
    id: 16,
    name: 'Mechanical Keyboard',
    image: '/dslr-camera-black.jpg',
    priceMin: 89,
    priceMax: 149,
    rating: 5,
    reviewCount: 63,
    inStock: true,
  },
  {
    id: 17,
    name: 'Webcam HD',
    image: '/wireless-mouse.png',
    priceMin: 45,
    priceMax: 79,
    rating: 4,
    reviewCount: 35,
    inStock: false,
    discountPercentage: 20,
  },
  {
    id: 18,
    name: 'Headset Pro',
    image: '/usb-c-hub-adapter.jpg',
    priceMin: 99,
    priceMax: 159,
    rating: 5,
    reviewCount: 51,
    inStock: true,
  },
  {
    id: 19,
    name: 'Monitor Stand',
    image: '/dslr-camera-black.jpg',
    priceMin: 29,
    priceMax: 49,
    rating: 4,
    reviewCount: 22,
    inStock: true,
    discountPercentage: 25,
  },
  {
    id: 20,
    name: 'Laptop Sleeve',
    image: '/wireless-mouse.png',
    priceMin: 19,
    priceMax: 35,
    rating: 3,
    reviewCount: 14,
    inStock: true,
  },
  {
    id: 21,
    name: 'External SSD 1TB',
    image: '/usb-c-hub-adapter.jpg',
    priceMin: 119,
    priceMax: 179,
    rating: 5,
    reviewCount: 78,
    inStock: true,
    discountPercentage: 10,
  },
  {
    id: 22,
    name: 'Wireless Charger',
    image: '/dslr-camera-black.jpg',
    priceMin: 29,
    priceMax: 49,
    rating: 4,
    reviewCount: 31,
    inStock: false,
  },
  {
    id: 23,
    name: 'Cable Organizer',
    image: '/wireless-mouse.png',
    priceMin: 12,
    priceMax: 18,
    rating: 5,
    reviewCount: 89,
    inStock: true,
    discountPercentage: 35,
  },
  {
    id: 24,
    name: 'Desk Lamp LED',
    image: '/usb-c-hub-adapter.jpg',
    priceMin: 39,
    priceMax: 69,
    rating: 4,
    reviewCount: 26,
    inStock: true,
  },
  {
    id: 25,
    name: 'Phone Stand',
    image: '/dslr-camera-black.jpg',
    priceMin: 15,
    priceMax: 25,
    rating: 4,
    reviewCount: 19,
    inStock: true,
    discountPercentage: 40,
  },
  {
    id: 26,
    name: 'Bluetooth Speaker',
    image: '/wireless-mouse.png',
    priceMin: 49,
    priceMax: 89,
    rating: 5,
    reviewCount: 44,
    inStock: true,
  },
  {
    id: 27,
    name: 'Screen Protector',
    image: '/usb-c-hub-adapter.jpg',
    priceMin: 9,
    priceMax: 19,
    rating: 3,
    reviewCount: 12,
    inStock: false,
    discountPercentage: 50,
  },
  {
    id: 28,
    name: 'Laptop Cooling Pad',
    image: '/dslr-camera-black.jpg',
    priceMin: 25,
    priceMax: 45,
    rating: 4,
    reviewCount: 37,
    inStock: true,
  },
];

export const camerasData: Product[] = [
  {
    id: 29,
    name: 'Canon EOS R5',
    image: '/dslr-camera-black.jpg',
    priceMin: 3899,
    priceMax: 4299,
    rating: 5,
    reviewCount: 45,
    inStock: true,
    discountPercentage: 5,
  },
  {
    id: 30,
    name: 'Sony A7 IV',
    image: '/dslr-camera-black.jpg',
    priceMin: 2499,
    priceMax: 2799,
    rating: 5,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: 31,
    name: 'Nikon Z6 II',
    image: '/dslr-camera-black.jpg',
    priceMin: 1999,
    priceMax: 2299,
    rating: 4,
    reviewCount: 32,
    inStock: false,
    discountPercentage: 15,
  },
  {
    id: 32,
    name: 'Fujifilm X-T4',
    image: '/dslr-camera-black.jpg',
    priceMin: 1699,
    priceMax: 1899,
    rating: 5,
    reviewCount: 28,
    inStock: true,
  },
  {
    id: 33,
    name: 'Panasonic Lumix GH5',
    image: '/dslr-camera-black.jpg',
    priceMin: 1399,
    priceMax: 1699,
    rating: 4,
    reviewCount: 38,
    inStock: true,
    discountPercentage: 20,
  },
  {
    id: 34,
    name: 'Canon EOS R6',
    image: '/dslr-camera-black.jpg',
    priceMin: 2499,
    priceMax: 2799,
    rating: 5,
    reviewCount: 52,
    inStock: true,
  },
  {
    id: 35,
    name: 'Sony A7R V',
    image: '/dslr-camera-black.jpg',
    priceMin: 3899,
    priceMax: 4199,
    rating: 5,
    reviewCount: 29,
    inStock: false,
    discountPercentage: 8,
  },
  {
    id: 36,
    name: 'Nikon Z9',
    image: '/dslr-camera-black.jpg',
    priceMin: 5499,
    priceMax: 5999,
    rating: 5,
    reviewCount: 41,
    inStock: true,
  },
  {
    id: 37,
    name: 'Olympus OM-1',
    image: '/dslr-camera-black.jpg',
    priceMin: 2199,
    priceMax: 2499,
    rating: 4,
    reviewCount: 24,
    inStock: true,
    discountPercentage: 12,
  },
  {
    id: 38,
    name: 'Leica Q2',
    image: '/dslr-camera-black.jpg',
    priceMin: 4995,
    priceMax: 5495,
    rating: 5,
    reviewCount: 18,
    inStock: true,
  },
];
